### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [Qubit-MU/Qiskit_Fall_Fest_2023#1]
I recently came across your project Qiskit_Fall_Fest_2023 and I noticed that the repository github.com/Qubit-MU/Qiskit_Fall_Fest_2023 currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by MU-Qubit** [comment]
Hello,

Thanks again for your suggestion! I’ve now added the Apache 2.0 license to the Qiskit Fall Fest 2023 repository. Feel free to check it out at your convenience.

If you have any further suggestions or feedback, I’d be happy to hear them.

Best regards,
Team Qubit.

**Comment by cbjuan** [comment]
thanks!
